### ISSUE TITLE
Style Grants PageHeader

### ISSUE THREAD

**Issue by mirhamasala** [FilecoinFoundationWeb/filecoin-foundation#65]
Style Grants PageHeader per Figma design [>>](https://www.figma.com/file/0pBfQs5tKI6bx5ypPIfVRA/FIL.org-V4-Prototypes?type=design&node-id=1393-26742&mode=design&t=MsngeYvwMnbHxHHV-4)

<img width="474" alt="Screenshot 2024-04-16 at 13 54 15" src="https://github.com/FilecoinFoundationWeb/filecoin-foundation/assets/26620750/1eeeffae-1c01-49ca-bd2c-9cdf2aa9dd0c">

**Comment by barbaraperic** [comment]
@mirhamasala @filipagr what do you think of having one paragraph below the title instead of breaking it in two? I'm asking because we have one property `description` which renders the text, in order to break the text in two, it would need an additional property and pass it as a prop (break lines don't seem to work), which I'm not sure if it's worth it? There's already similar structure in Ecosystem page. Thoughts?

![Screenshot 2024-04-16 at 14 56 47](https://github.com/FilecoinFoundationWeb/filecoin-foundation/assets/50910606/f50eb5dd-9b2a-4ead-975b-e8fdbb0dbfeb)

![Screenshot 2024-04-16 at 15 13 51](https://github.com/FilecoinFoundationWeb/filecoin-foundation/assets/50910606/a8aa81e2-eff6-4051-85f4-5fca08e36605)

**Comment by mirhamasala** [comment]
> It would need an additional property and pass it as a prop

@barbaraperic You can change the `description` prop to also accept an array of strings - ` description: string | string[]; `. Then, something like:

```
function Description({ description }) {
  if (Array.isArray(description)) {
    return (
      <div className="space-y-4">
        {description.map((paragraph, index) => (
          <p key={index}>{paragraph}</p>
        ))}
      </div>
    );
  }
  return <p>{description}</p>;
}
``` 

---

Another solution would be to pass a delimiter like `/n` and split the string on it like below (but I don't like this solution because you would have to keep it updated across the project and it's not clear immediately it's possible by just looking at the type definition of `PageHeader`:

```
<p>
  {description.split('\n').map((paragraph, index) => (
    <span key={index}>{paragraph}</span>
  ))}
</p>
```

**Comment by barbaraperic** [comment]
Nice 🙂 I like the first solution
